{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fake-mariadb.serviceAccountName" . }}
  labels:
{{ include "fake-mariadb.labels" . | nindent 4 }}
{{- end -}}
